version: '3'

services:
  identity:
    env_file:
      - ./var1.env
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    ports:
      - "5002:80"
networks:
  default:
    external:
      name: nat
