version: '3.4'

services:
  identity:
    env_file:
      - ./var1.env
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    volumes:
      - /C/ei8/identity:/C/db
    ports:
      - 192.168.8.131:60700:80